services:
  qemu-vm:
    build: .
    container_name: ubuntu
    environment:
      BOOT: "ubuntu"
      CPU_CORES: "4"
      RAM_SIZE: "8G"
      DISK_SIZE: "20G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 8007:8007
    volumes:
      - ./storage:/storage
    restart: always
    stop_grace_period: 2m
